Traceback (most recent call last):
  File "main.py", line 109, in main
    app = pm.MainApplication(parse_parameters())
  File "D:\PycharmProjects\pythonProject\PM\parameters.py", line 153, in parse_parameters
    return vars(parser.parse_args())
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "C:\ProgramData\Anaconda3\envs\pythonProject\lib\argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "D:\PycharmProjects\pythonProject\PM\parameters.py", line 28, in __call__
    raise ArgumentTypeError("readable_dir:{} is not a valid path".format(prospective_dir))
argparse.ArgumentTypeError: readable_dir:D:/PycharmProjects/pythonProject/perfect_match-master/perfect_match-master/perfect_match/apps is not a valid path
